main:
  - name: Hakkımda
    url: '#hakkimda'
    weight: 10
  - name: Araştırma
    url: '#alanlar'
    weight: 20
  - name: Yayınlar
    url: '#yayinlar'
    weight: 30
  - name: Projeler
    url: '#projeler'
    weight: 40
  - name: Dersler
    url: '#dersler'
    weight: 50
  - name: İletişim
    url: '#iletisim'
    weight: 60
  - name: CV
    url: 'https://byuzbasi.github.io/uploads/Resume_Bahadir_Yuzbasi.pdf'
    weight: 70
